In [1]:
# 例題１．１

In [2]:
#numpyの基本：等間隔の数値列
import numpy as np

#整数の場合
a1 = np.arange(0, 11, 1)
print("a1=", a1)
#実数の場合
a2 = np.arange(0, 1.1, 0.1)
print("a2=", a2)

a1= [ 0  1  2  3  4  5  6  7  8  9 10]
a2= [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [3]:
#例題１．２

In [4]:
#numpyの基本：乱数生成
import numpy as np

#0~1の一様分布の乱数
a1 = np.random.rand(5)
print("a1=")
print(a1)
#整数型の一様分布の乱数
a2 = np.random.randint(1, 101, (3, 3))
print("a2=")
print(a2)

a1=
[0.80016168 0.98382581 0.17401217 0.28761103 0.95107452]
a2=
[[22 69  1]
 [84 25 77]
 [87 92 76]]


In [5]:
#例題１．３

In [6]:
import numpy as np

#２次元の０値配列
a1 = np.zeros((3, 4))
print(a1)

#２次元の１値配列
a2 = np.ones((3, 4))
print(a2)

#単位行列
a3 = np.eye(3)
print(a3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
#例題１．４

In [9]:
import numpy as np

a1 = np.array([[1, 1, 1],
               [1, 1, 1],
               [1, 1, 1]])
print(a1)

a2 = np.array([[2, 2, 2],
               [2, 2, 2],
               [2, 2, 2]])
print(a2)

#行列の縦結合
a3 = np.concatenate([a1, a2], axis=0)
print(a3)

#行列の横結合
a4 = np.concatenate([a1, a2], axis=1)
print(a4)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]
 [2 2 2]]
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [1 1 1 2 2 2]]
